### ISSUE TITLE
add delete experiment function

### ISSUE THREAD

**Issue by WhyYouNeedMyUsername** [MoBagel/decanter-ai-sdk#38]
At times, it may be necessary to delete specific experiments. However, the Decanter AI SDK currently does not provide this functionality. Below is an example of how I implemented the feature through the API.

```
experiment_id_name = {}
for page in range(4):
    for id, content in client.get_experiment_list(page=page).items():    
        requests.post(
            f"{client.api.url}experiment/delete",
            data=json.dumps({"project_id": client.api.project_id, "experiment_id": id}),
            headers=client.api.headers,
            verify=False,
        )
        print("delete!", id, content['ExperimentName'])
```

**Comment by jimliu-gbd** [comment]
nice suggestion~ 
Already added this functionality. 
More detail on the commit "08506edee0a815520a95707431ab836658bdd402"
